task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('control/', include('quality_control.urls')),
]

task_manager/tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('another/', views.another_page, name='another_page'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetaiView.as_view(), name='task_detail'),
    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
    path('projects/create/', views.CreatProjectView.as_view(), name='project_create'),
    path('projects/<int:project_id>/add_task/', views.AddTaskView.as_view(), name='add_task'),
    path('projects/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='project_update'),
    path('projects/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='task_update'),
    path('projects/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('projects/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='task_delete'),
]

task_manager/tasks/models.py
from django.db import models
from django.contrib.auth.models import User

class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
class Task(models.Model):
    STATUS_CHOICES = [
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена'),
    ]
    project = models.ForeignKey(
        Project,
        related_name='tasks',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    assignee = models.ForeignKey(
        User,
        related_name='tasks',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New',
    )
    
    def __str__(self):
        return self.name

task_manager/tasks/forms.py
from django import forms
from django.forms import ModelForm
from .models import Project, Task

class FeedbackForm(forms.Form):
    name = forms.CharField(label="Ваше имя", max_length=100)
    email = forms.EmailField(label="Электронная почта")
    message = forms.CharField(widget=forms.Textarea, label="Сообщение")

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description"]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["name", "description", "status", "assignee"]

task_manager/tasks/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, TemplateView, FormView, CreateView, UpdateView, DeleteView
from .models import Project, Task
from .forms import FeedbackForm, ProjectForm, TaskForm

def another_page(requset):
    return HttpResponse('Это другая страница приложения tasks')


class IndexView(TemplateView):
    template_name = 'tasks/index.html'
    
    
class ProjectsListView(ListView):
    model = Project
    context_object_name = 'projects_list'
    template_name = 'tasks/projects_list.html'

class ProjectDetailView(DetailView):
    model = Project
    pk_url_kwarg = 'project_id'
    template_name = 'tasks/project_detail.html'

class TaskDetaiView(DetailView):
    model = Task
    pk_url_kwarg = 'task_id'
    template_name = 'tasks/task_detail.html'

class FeedbackView(FormView):
    form_class = FeedbackForm
    success_url = reverse_lazy('tasks:index')
    template_name = "tasks/feedback.html"

class CreatProjectView(CreateView):
    form_class = ProjectForm
    success_url = reverse_lazy('tasks:projects_list')
    template_name = "tasks/project_create.html"

class AddTaskView(CreateView):
    form_class = TaskForm
    pk_url_kwarg = 'task_id'
    template_name = "tasks/add_task.html"
    def form_valid(self, form: TaskForm) -> HttpResponse:
        task = form.instance
        project = get_object_or_404(Project, pk=self.kwargs["project_id"])
        task.project = project
        return super().form_valid(form)
    
    def get_success_url(self) -> str:
        return reverse("tasks:project_detail", kwargs={"project_id": self.kwargs["project_id"]})
    
class ProjectUpdateView(UpdateView):
    model = Project
    form_class = ProjectForm
    pk_url_kwarg = "project_id"
    success_url = reverse_lazy('tasks:projects_list')
    template_name = "tasks/project_update.html"
    
class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/task_update.html"
    pk_url_kwarg = 'task_id'
    
    def get_success_url(self) -> str:
        project_id = self.object.project.id
        task_id = self.object.id
        
        return reverse_lazy("tasks:task_detail", kwargs={"project_id": project_id, "task_id": task_id})
    
class ProjectDeleteView(DeleteView):
    model = Project
    pk_url_kwarg = "project_id"
    success_url = reverse_lazy('tasks:projects_list')
    template_name="tasks/project_confirm_delete.html"
    
class TaskDeleteView(DeleteView):
    model = Task
    pk_url_kwarg = "task_id"
    template_name="tasks/task_confirm_delete.html"
    
    def get_success_url(self) -> str:
        return reverse("tasks:project_detail", kwargs={"project_id": self.kwargs["project_id"]})
        

task_manager/tasks/templates/tasks/add_task.html
{% extends "base/base.html" %}
{% block content%}

<h2>Доавить новую задачу в проект {{ project.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>

{% endblock %}

task_manager/tasks/templates/tasks/feedback.html
{% extends "base/base.html" %}
{% block content  %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>

{% endblock  %}

task_manager/tasks/templates/tasks/index.html
{% extends "base/base.html" %}
{% block content %}

    <h1>Страница приложения tasks</h1>
    <a href="{% url 'tasks:projects_list' %}">Список проектов</a>

{% endblock %}

task_manager/tasks/templates/tasks/project_confirm_delete.html
{% extends 'base/base.html'%}
{% block content %}

    <h1>Удаление проекта</h1>
    <p>Вы уверены, что хотите удалить проект {{ project.name }}?</p>
    
    <form action={% url "tasks:project_delete" project.id %} method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href={% url "tasks:project_detail" project.id %}>Отмена</a>
    </form>
    
    
{% endblock %}

task_manager/tasks/templates/tasks/project_create.html
{% extends "base/base.html" %}
{% block content%}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<h2>Создать новый проект</h2>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }}
            {{ field }}
        {% endfor %}
        <button type="submit">Создать</button>
    </form>

{% endblock %}

task_manager/tasks/templates/tasks/project_detail.html
{% extends 'base/base.html'%}
{% block content %}

    <h1>{{ project.name }}</h1>
    <p>{{ project.description }}</p>
    <p><a href={% url 'tasks:project_update' project.id %}>Изменить проект</a></p>
    <p><a href={% url 'tasks:add_task' project.id %}>Добавить задачу</a></p>
    <p><a href={% url 'tasks:project_delete' project.id  %} >Удалить проект</a></p>
    <ul>
        {% for task in project.tasks.all %}
            <li><a href="{% url 'tasks:task_detail' project.id task.id %}">{{ task.name }}</a> - {{ task.status }}</li>
        {% empty %}
            <li>В этом проекте пока нет задач.</li>
        {% endfor %}
    </ul>
    
{% endblock %}

task_manager/tasks/templates/tasks/project_update.html
{% extends "base/base.html" %}
{% block content%}

<h2>Изменить проект</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>

{% endblock %}

task_manager/tasks/templates/tasks/projects_list.html
{% extends 'base/base.html'%}
{% block content %}

    <h1>Список проектов</h1>
    <p><a href={% url 'tasks:project_create'%}>Создать проект</a></p>
    <ul>
        {% for project in projects_list %}
            <li><a href="{% url 'tasks:project_detail' project.id %}">{{ project.name }}</a></li>
        {% endfor %}
    </ul>
    
    
{% endblock %}

task_manager/tasks/templates/tasks/task_confirm_delete.html
{% extends 'base/base.html'%}
{% block content %}

    <h1>Удаление задачи</h1>
    <p>Вы уверены, что хотите удалить задачу {{ task.name }}?</p>
    
    <form action={% url "tasks:task_delete" task.project.id task.id %} method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href={% url "tasks:task_detail" task.project.id task.id %}>Отмена</a>
    </form>
    
    
{% endblock %}

task_manager/tasks/templates/tasks/task_detail.html
{% extends 'base/base.html'%}
{% block content %}

    <h1>{{ task.name }}</h1>
    <p><a href={% url "tasks:task_update" task.project.id task.id %}>Изменить задачу</a></p>
    <p><a href={% url "tasks:task_delete" task.project.id task.id %} >Удалить задачу</a></p>
    <p>{{ task.description }}</p>
    
{% endblock %}

task_manager/tasks/templates/tasks/task_update.html
{% extends "base/base.html" %}
{% block content%}

<h2>Изменить задачу {{ project.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>

{% endblock %}