task_manager/quality_control/urls.py
from django.urls import path, include
from .views import *

app_name = 'quality_control'

class_view = True

if class_view:
    urlpatterns = [
        path('', IndexView.as_view(), name="index"),
        path('bugs/', BugReportsListView.as_view(), name='bugs'),
        path('bugs/<int:bug_id>/', BugReportView.as_view(), name='bug_details'),
        path('bugs/add_bug_report/', BugReportCreateView.as_view(), name='bug_add'),
        path('bugs/<int:bug_id>/update/', BugReportUpdateView.as_view(), name='bug_update'),
        path('bugs/<int:bug_id>/delete/', BugReportDeleteView.as_view(), name='bug_delete' ),
        
        
        path('features/', FeatureRequestsListView.as_view(), name='features'),
        path('features/<int:feature_id>/', FeatureRequestView.as_view(), name='feature_details'),
        path('features/add_feature_request', FeatureRequestCreateView.as_view(), name='feature_add'),
        path('features/<int:feature_id>/update/', FeatureRequestUpdateView.as_view(), name='feature_update'),
        path('features/<int:feature_id>/delete/', FeatureRequestDeleteView.as_view(), name='feature_delete'),
    ]
else:
    urlpatterns = [
        path('', index , name="index"),
        
        path('bugs/', bugs, name='bugs'),
        path('bugs/<int:bug_id>/', bug_details, name='bug_details'),
        path('bugs/add_bug_report/', bug_add, name='bug_add'),
        path('bugs/<int:bug_id>/update/', bug_update, name='bug_update'),
        path('bugs/<int:bug_id>/delete/', bug_delete, name='bug_delete' ),
        
        path('features/', features, name='features'),
        path('features/<int:feature_id>/', feature_details, name='feature_details'),
        path('features/add_feature_request', feature_add, name='feature_add'),
        path('features/<int:feature_id>/update/', feature_update, name='feature_update'),
        path('features/<int:feature_id>/delete/', feature_delete, name='feature_delete'),
    ]
 

task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('control/', include('quality_control.urls')),
]

task_manager/tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('another/', views.another_page, name='another_page'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetaiView.as_view(), name='task_detail'),
    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
    path('projects/create/', views.CreatProjectView.as_view(), name='project_create'),
    path('projects/<int:project_id>/add_task/', views.AddTaskView.as_view(), name='add_task'),
    path('projects/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='project_update'),
    path('projects/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='task_update'),
    path('projects/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('projects/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='task_delete'),
]

task_manager/quality_control/models.py
from django.db import models
from django.forms import ValidationError
from tasks.models import Project, Task
from django.core.validators import MaxValueValidator, MinValueValidator

class BugReport(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        related_name="project_report",
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        related_name="task_report",
        null=True,
        on_delete=models.SET_NULL
    )
    STATUS_CHOICES = { "New":"Новая", "In_pogress": "В работе", "Completed":"Завершена" }
    status = models.CharField(choices=STATUS_CHOICES, default="New", max_length=50)
    priority = models.IntegerField(default=1, validators=[MaxValueValidator(5), MinValueValidator(1)])
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    def clean(self):
        super().clean()
        if self.task and self.project != self.task.project:
            raise ValidationError("Задача должна относиться к выбранному проекту")

class FeatureRequest(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        related_name="project_feature",
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        null=True,
        related_name="task_feature",
        on_delete=models.SET_NULL
    )
    STATUS_CHOICES = { "Under_consideration":"Рассматривается", "Accepted": "Принята", "Rejected":"Отклонена" }
    status = models.CharField(choices=STATUS_CHOICES, default="Under_consideration", max_length=50)
    priority = models.IntegerField(default=1, validators=[MaxValueValidator(5), MinValueValidator(1)])
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    def clean(self):
        super().clean()
        if self.task and self.project != self.task.project:
            raise ValidationError("Задача должна относиться к выбранному проекту")

task_manager/quality_control/forms.py
from django.forms import ModelForm
from django import forms
from tasks.models import Task, Project 
from .models import *

class BugReportForm(ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']
        labels = {'title': 'Название', 'description': 'Описание', 'status': 'Статус', 'priority':'Приоритет', 'project':'Проект', 'task':'Задача'}
        
class FeatureRequestForm(ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']
        labels = {'title': 'Название', 'description': 'Описание', 'status': 'Статус', 'priority':'Приоритет', 'project':'Проект', 'task':'Задача'}

task_manager/quality_control/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.template import loader
from django.views.generic import TemplateView, DetailView, ListView, FormView, CreateView, UpdateView, DeleteView
from .models import *
from .forms import *
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect

#region FBV
def index(request):
    return render(request, 'quality_control/index.html')


def bugs(request):
    bugs_list =  get_list_or_404(BugReport)
    context = {'bugs_list': bugs_list}
    return render(request, 'quality_control/bugs_list.html', context)

def bug_details(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    context = {'bug': bug}
    return render(request, 'quality_control/bug_details.html', context)

def bug_add(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('quality_control:bugs'))
    else:   
        form = BugReportForm()
        
    context = {'form': form}
    return render(request, 'quality_control/bug_report_form.html', context)

def bug_update(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('quality_control:bug_details', kwargs={"bug_id": bug_id}))
    else:   
        form = BugReportForm(instance=bug)
    context = {'form': form}
    return render(request, 'quality_control/bug_update_form.html', context)

def bug_delete(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    if request.method == 'POST':
        bug.delete()
        return redirect(reverse_lazy('quality_control:bugs'))
    return render(request, 'quality_control/bug_delete.html', {'bug': bug})
        
        
def features(request):
    features_list =  get_list_or_404(FeatureRequest)
    context = {'features_list': features_list}
    return render(request, 'quality_control/features_list.html', context)

def feature_details(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    context = {'feature': feature}
    return render(request, 'quality_control/feature_details.html', context)

def feature_add(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('quality_control:features'))
    else:   
        form = FeatureRequestForm()
        
    context = {'form': form}
    return render(request, 'quality_control/feature_request_form.html', context)

def feature_update(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('quality_control:feature_details', kwargs={"feature_id": feature_id}))
    else:   
        form = FeatureRequestForm(instance=feature)
    context = {'form': form}
    return render(request, 'quality_control/feature_update_form.html', context)

def feature_delete(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    if request.method == 'POST':
        feature.delete()
        return redirect(reverse_lazy('quality_control:features'))
    return render(request, 'quality_control/feature_delete.html', {'feature': feature})

#endregion

#region CBV
class IndexView(TemplateView):
    template_name = 'quality_control/index.html'
    
    
class BugReportsListView(ListView):
    template_name = 'quality_control/bugs_list.html'
    model = BugReport
    context_object_name = 'bugs_list'


class BugReportView(DetailView):
    model = BugReport
    context_object_name = 'bug'
    pk_url_kwarg = 'bug_id'
    template_name='quality_control/bug_details.html'
    
class BugReportCreateView(CreateView):
    form_class = BugReportForm
    success_url = reverse_lazy('quality_control:bugs')
    template_name = 'quality_control/bug_report_form.html'
    
class BugReportUpdateView(UpdateView):
    form_class = BugReportForm
    model = BugReport
    pk_url_kwarg = 'bug_id'
    template_name = 'quality_control/bug_update_form.html'
    def get_success_url(self) -> str:
        return reverse('quality_control:bug_details', kwargs={'bug_id': self.kwargs['bug_id']})
    
class BugReportDeleteView(DeleteView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    context_object_name = 'bug'
    template_name = 'quality_control/bug_delete.html'
    success_url = reverse_lazy('quality_control:bugs')
    

class FeatureRequestsListView(ListView):
    template_name = 'quality_control/features_list.html'
    model = FeatureRequest
    context_object_name = 'features_list'
    

class FeatureRequestView(DetailView):
    model = FeatureRequest
    context_object_name = 'feature'
    pk_url_kwarg = 'feature_id'
    template_name='quality_control/feature_details.html'
    
class FeatureRequestCreateView(CreateView):
    form_class = FeatureRequestForm
    success_url = reverse_lazy('quality_control:features')
    template_name = 'quality_control/feature_request_form.html'
    
class FeatureRequestUpdateView(UpdateView):
    form_class = FeatureRequestForm
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    template_name = 'quality_control/feature_update_form.html'
    def get_success_url(self) -> str:
        return reverse('quality_control:feature_details', kwargs={'feature_id': self.kwargs['feature_id']})
    
class FeatureRequestDeleteView(DeleteView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    context_object_name = 'feature'
    template_name = 'quality_control/feature_delete.html'
    success_url = reverse_lazy('quality_control:features')
#endregion

task_manager/quality_control/templates/quality_control/bug_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление сообщения об ошибке</h1>
    <p>Вы уверены, что хотите удалить сообщение"{{ bug.title }}"?</p>

    <form action="{% url 'quality_control:bug_delete' bug.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bug_details' bug.id %}">Отмена</a>
    </form>
{% endblock %}

task_manager/quality_control/templates/quality_control/bug_details.html
{% extends 'base/base.html'%}
{% block content %}

    <h1>{{ bug.title }}</h1>
    <p>Описание: {{ bug.description }}</p>
    <p>Проект: {{ bug.project.name }}</p>
    <p>Задача: {{ bug.task.name }}</p>
    <p>Статус: {{ bug.get_status_display }} </p>
    <p>
        <a href={% url 'quality_control:bug_update' bug.id %}>Изменить</a>
        <a href={% url 'quality_control:bug_delete' bug.id %}>Удалить</a>
    </p>
    
{% endblock %}

task_manager/quality_control/templates/quality_control/bug_report_form.html
{% extends "base/base.html" %}
{% block content%}
<h2>Сообщение об ошибке</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Добавить">
</form>

{% endblock %}

task_manager/quality_control/templates/quality_control/bug_update_form.html
{% extends "base/base.html" %}
{% block content%}
<h2>Изменить сообщение об ошибке</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Сохранить">
</form>

{% endblock %}

task_manager/quality_control/templates/quality_control/bugs_list.html
{% extends 'base/base.html'%}
{% block content %}

    <h1>Список багов</h1>
    {% if bugs_list %}
    <ul>
        {% for bug in bugs_list %}
            <li><a href={% url 'quality_control:bug_details' bug.id %}>{{ bug.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <h2>Пока багов не обнаружено</h2>
    {% endif %}
    <p><a href={% url 'quality_control:bug_add' %}>Добавить отчет</a></p>
    
    
{% endblock %}

task_manager/quality_control/templates/quality_control/feature_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса на улучшение</h1>
    <p>Вы уверены, что хотите удалить запрос"{{ feature.title }}"?</p>

    <form action="{% url 'quality_control:feature_delete' feature.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feature_details' feature.id %}">Отмена</a>
    </form>
{% endblock %}

task_manager/quality_control/templates/quality_control/feature_details.html
{% extends 'base/base.html'%}
{% block content %}

    <h1>{{ feature.title }}</h1>
    <p>Описание: {{ feature.description }}</p>
    <p>Проект: {{ feature.project.name }}</p>
    <p>Задача: {{ feature.task.name }}</p>
    <p>Статус: {{ feature.get_status_display }} </p>
    <p>
        <a href={% url 'quality_control:feature_update' feature.id %}>Изменить</a>
        <a href={% url 'quality_control:feature_delete' feature.id %}>Удалить</a>
    </p>
{% endblock %}

task_manager/quality_control/templates/quality_control/feature_request_form.html
{% extends "base/base.html" %}
{% block content%}
<h2>Изменить Запросапрос на улучшение</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Добавить">
</form>

{% endblock %}

task_manager/quality_control/templates/quality_control/feature_update_form.html
{% extends "base/base.html" %}
{% block content%}
<h2>Запрос на улучшение</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Сохранить">
</form>

{% endblock %}

task_manager/quality_control/templates/quality_control/features_list.html
{% extends 'base/base.html'%}
{% block content %}

    <h1>Список улучшений</h1>
    {% if features_list %}
    <ul>
        
        {% for feature in features_list %}
            <li><a href={% url "quality_control:feature_details" feature.id %}>{{ feature.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <h2>Пока улучшений не предложено</h2>
    {% endif %}
    <p><a href={% url 'quality_control:feature_add' %}>Предложить улучшение</a></p>
    
{% endblock %}

task_manager/quality_control/templates/quality_control/index.html
{% extends "base/base.html" %}
{% block content %}
<h1>Система контроля качества</h1>
<p><a href={% url "quality_control:bugs" %}>Список всех багов</a></p>
<p><a href={% url "quality_control:features" %}>Запросы на улучшения</a></p>
{% endblock%}